version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sprintprep_postgres
    restart: always
    environment:
      POSTGRES_USER: sprintuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sprintprep
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
